export const keyboardLayout = [
    [
        {code: 'Backquote', ru: 'ё', ruShift: 'Ё', en: '`', enShift: '~', type: 'simple'},
        {code: 'Digit1', ru: '1', ruShift: '!', en: '1', enShift: '!', type: 'simple'},
        {code: 'Digit2', ru: '2', ruShift: '"', en: '2', enShift: '@', type: 'simple'},
        {code: 'Digit3', ru: '3', ruShift: '№', en: '3', enShift: '#', type: 'simple'},
        {code: 'Digit4', ru: '4', ruShift: ';', en: '4', enShift: '$', type: 'simple'},
        {code: 'Digit5', ru: '5', ruShift: '%', en: '5', enShift: '%', type: 'simple'},
        {code: 'Digit6', ru: '6', ruShift: ':', en: '6', enShift: '^', type: 'simple'},
        {code: 'Digit7', ru: '7', ruShift: '?', en: '7', enShift: '&', type: 'simple'},
        {code: 'Digit8', ru: '8', ruShift: '*', en: '8', enShift: '*', type: 'simple'},
        {code: 'Digit9', ru: '9', ruShift: '(', en: '9', enShift: '(', type: 'simple'},
        {code: 'Digit0', ru: '0', ruShift: ')', en: '0', enShift: ')', type: 'simple'},
        {code: 'Minus', ru: '-', ruShift: '_', en: '-', enShift: '_', type: 'simple'},
        {code: 'Equal', ru: '=', ruShift: '+', en: '=', enShift: '+', type: 'simple'},
        {code: 'Backspace', ru: 'Backspace', ruShift: 'Backspace', en: 'Backspace', enShift: 'Backspace', type: 'func'},
    ],
    [
        {code: 'Tab', ru: 'Tab', ruShift: 'Tab', en: 'Tab', enShift: 'Tab', type: 'func'},
        {code: 'KeyQ', ru: 'й', ruShift: 'Й', en: 'q', enShift: 'Q', type: 'simple'},
        {code: 'KeyW', ru: 'ц', ruShift: 'Ц', en: 'w', enShift: 'W', type: 'simple'},
        {code: 'KeyE', ru: 'у', ruShift: 'У', en: 'e', enShift: 'E', type: 'simple'},
        {code: 'KeyR', ru: 'к', ruShift: 'К', en: 'r', enShift: 'R', type: 'simple'},
        {code: 'KeyT', ru: 'е', ruShift: 'Е', en: 't', enShift: 'T', type: 'simple'},
        {code: 'KeyY', ru: 'н', ruShift: 'Н', en: 'y', enShift: 'Y', type: 'simple'},
        {code: 'KeyU', ru: 'г', ruShift: 'Г', en: 'u', enShift: 'U', type: 'simple'},
        {code: 'KeyI', ru: 'ш', ruShift: 'Ш', en: 'i', enShift: 'I', type: 'simple'},
        {code: 'KeyO', ru: 'щ', ruShift: 'Щ', en: 'o', enShift: 'O', type: 'simple'},
        {code: 'KeyP', ru: 'з', ruShift: 'З', en: 'p', enShift: 'P', type: 'simple'},
        {code: 'BracketLeft', ru: 'х', ruShift: 'Х', en: '[', enShift: '{', type: 'simple'},
        {code: 'BracketRight', ru: 'ъ', ruShift: 'Ъ', en: ']', enShift: '}', type: 'simple'},
        {code: 'Delete', ru: 'Del', ruShift: 'Del', en: 'Del', enShift: 'Del', type: 'func'},
    ],
    [
        {code: 'CapsLock', ru: 'Caps', ruShift: 'Caps', en: 'Caps', enShift: 'Caps', type: 'func'},
        {code: 'KeyA', ru: 'ф', ruShift: 'Ф', en: 'a', enShift: 'A', type: 'simple'},
        {code: 'KeyS', ru: 'ы', ruShift: 'Ы', en: 's', enShift: 'S', type: 'simple'},
        {code: 'KeyD', ru: 'в', ruShift: 'В', en: 'd', enShift: 'D', type: 'simple'},
        {code: 'KeyF', ru: 'а', ruShift: 'А', en: 'f', enShift: 'F', type: 'simple'},
        {code: 'KeyG', ru: 'п', ruShift: 'П', en: 'g', enShift: 'G', type: 'simple'},
        {code: 'KeyH', ru: 'р', ruShift: 'Р', en: 'h', enShift: 'H', type: 'simple'},
        {code: 'KeyJ', ru: 'о', ruShift: 'О', en: 'j', enShift: 'J', type: 'simple'},
        {code: 'KeyK', ru: 'л', ruShift: 'Л', en: 'k', enShift: 'K', type: 'simple'},
        {code: 'KeyL', ru: 'д', ruShift: 'Д', en: 'l', enShift: 'L', type: 'simple'},
        {code: 'Semicolon', ru: 'ж', ruShift: 'Ж', en: ';', enShift: ':', type: 'simple'},
        {code: 'Quote', ru: 'э', ruShift: 'Э', en: '\'', enShift: '"', type: 'simple'},
        {code: 'Backslash', ru: '\\', ruShift: '/', en: '\\', enShift: '|', type: 'simple'},
        {code: 'Enter', ru: 'Enter', ruShift: 'Enter', en: 'Enter', enShift: 'Enter', type: 'func'},
    ],
    [
        {code: 'ShiftLeft', ru: 'Shift', ruShift: 'Shift', en: 'Shift', enShift: 'Shift', type: 'func'},
        {code: 'KeyZ', ru: 'я', ruShift: 'Я', en: 'z', enShift: 'Z', type: 'simple'},
        {code: 'KeyX', ru: 'ч', ruShift: 'Ч', en: 'x', enShift: 'X', type: 'simple'},
        {code: 'KeyC', ru: 'с', ruShift: 'С', en: 'c', enShift: 'C', type: 'simple'},
        {code: 'KeyV', ru: 'м', ruShift: 'М', en: 'v', enShift: 'V', type: 'simple'},
        {code: 'KeyB', ru: 'и', ruShift: 'И', en: 'b', enShift: 'B', type: 'simple'},
        {code: 'KeyN', ru: 'т', ruShift: 'Т', en: 'n', enShift: 'N', type: 'simple'},
        {code: 'KeyM', ru: 'ь', ruShift: 'Ь', en: 'm', enShift: 'M', type: 'simple'},
        {code: 'Comma', ru: 'б', ruShift: 'Б', en: ',', enShift: '<', type: 'simple'},
        {code: 'Period', ru: 'ю', ruShift: 'Ю', en: '.', enShift: '>', type: 'simple'},
        {code: 'Slash', ru: '.', ruShift: ',', en: '/', enShift: '?', type: 'simple'},
        {code: 'ArrowUp', ru: '↑', ruShift: '↑', en: '↑', enShift: '↑', type: 'func'},
        {code: 'ShiftRight', ru: 'Shift', ruShift: 'Shift', en: 'Shift', enShift: 'Shift', type: 'func'},
    ],
    [
        {code: 'ControlLeft', ru: 'Ctrl', ruShift: 'Ctrl', en: 'Ctrl', enShift: 'Ctrl', type: 'func'},
        {code: 'AltLeft', ru: 'Alt', ruShift: 'Alt', en: 'Alt', enShift: 'Alt', type: 'func'},
        {code: 'Space', ru: 'Space', ruShift: 'Space', en: 'Space', enShift: 'Space', type: 'func'},
        {code: 'ArrowLeft', ru: '←', ruShift: '←', en: '←', enShift: '←', type: 'func'},
        {code: 'ArrowDown', ru: '↓', ruShift: '↓', en: '↓', enShift: '↓', type: 'func'},
        {code: 'ArrowRight', ru: '→', ruShift: '→', en: '→', enShift: '→', type: 'func'},
        {code: 'ControlRight', ru: 'Ctrl', ruShift: 'Ctrl', en: 'Ctrl', enShift: 'Ctrl', type: 'func'},
    ]
]